Update GenerateFridaSnippetForDex.py
IsVoid no longer exists ? 
Replacing it with a check on the name of the type.

[E] Script execution error: com.pnfsoftware.jeb.client.script.ScriptExecutionException: Traceback (most recent call last):
[E]   File "/jeb5/scripts/samples/GenerateFridaSnippetForDex.py", line 58, in run
[E]     no_return = m.getReturnType().isVoid()
[E] AttributeError: 'com.pnfsoftware.jebglobal.xW' object has no attribute 'isVoid'
[E]